<?php

namespace AppBundle\Repository;

/**
 * DetailVoyageRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class DetailVoyageRepository extends \Doctrine\ORM\EntityRepository
{
}
