<?php

namespace AppBundle\Repository;

/**
 * DonneurOrdreRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class DonneurOrdreRepository extends \Doctrine\ORM\EntityRepository
{
}
