<?php

namespace AppBundle\Repository;

use Doctrine\ORM\Mapping;

/**
 * GestionRetourRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class GestionRetourRepository extends \Doctrine\ORM\EntityRepository
{


    public function findInStock()
    {
        $em = $this->getEntityManager();
        $query = $em->createQuery(
            'SELECT g
                    FROM AppBundle:GestionRetour g
                    WHERE g.dateSortieEntrepot = :dateSortie'
                        )->setParameter('dateSortie', '2000-01-01');

        return $query->getResult();
    }
}