<?php

namespace AppBundle\Repository;

/**
 * HistoriqueGestionRetourRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class HistoriqueGestionRetourRepository extends \Doctrine\ORM\EntityRepository
{

}
