<?php

namespace AppBundle\Repository;

/**
 * MotifRetourRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class MotifRetourRepository extends \Doctrine\ORM\EntityRepository
{
}
