<?php

namespace AppBundle\Repository;

/**
 * RattachementRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class RattachementRepository extends \Doctrine\ORM\EntityRepository
{
}
