<?php

namespace AppBundle\Repository;

/**
 * VoyageRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class VoyageRepository extends \Doctrine\ORM\EntityRepository
{

    public function findInStock($idAgence)
    {
        $query = $this->createQueryBuilder('g')
            ->select('g', 'm','d','r')
            ->join('g.magasin', 'm')
            ->join('g.donneurOrdre', 'd')
            ->join('d.rattachement', 'r')
            ->where('g.dateSortieEntrepot IS NULL')
            ->andWhere('g.agence = :agence')
            ->orderBy('g.dateSortieEntrepot')
            ->setParameter('agence', $idAgence)
            ->getQuery();

        return $query->getResult();
    }
}
