security:
    encoders:
        FOS\UserBundle\Model\UserInterface: bcrypt

    role_hierarchy:
        ROLE_USER:          ROLE_USER
        ROLE_MAGASINIER:    ROLE_USER
        ROLE_EXPLOITANT:    ROLE_EXPLOITANT
        ROLE_DIRECTEUR:     ROLE_ADMIN
        ROLE_ADMIN:         ROLE_ADMIN
        ROLE_SUPER_ADMIN:   ROLE_SUPER_ADMIN

    providers:
        fos_userbundle:
            id: fos_user.user_provider.username

    firewalls:
        main:
            pattern: ^/
            form_login:
                provider: fos_userbundle
                csrf_token_generator: security.csrf.token_manager

            logout:       true
            anonymous:    true

    access_control:
        - { path: ^/login$, role: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/register, role: ROLE_ADMIN }
        - { path: ^/resetting, role: ROLE_USER }
        - { path: ^/admin/, role: ROLE_ADMIN }
        - { path: ^/gestion/, role: ROLE_ADMIN }
        - { path: /edit, role: ROLE_ADMIN }
        - { path: ^/, role: ROLE_USER }

